# This action generates a weekly report as a github issue
# More details in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24672

name: 'Generate Weekly Report'
on:
  workflow_dispatch: 
  push:
    branches: [ chore/weekly-report-gen ]

jobs:
  get_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install js-yaml
        working-directory: ./.github/workflows/scripts
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/github-script@v6
        id: get-issues
        with:
          retries: 3
          script: |
            const script = require('.github/workflows/scripts/generate-weekly-report.js')
            await script({github, context})